# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import timeit
import os
import Choose

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 611)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 120, 71, 41))
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 71, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 71, 41))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 270, 71, 41))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 101, 41))
        self.label_5.setStyleSheet("color: rgb(238, 122, 233);font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 330, 101, 41))
        self.label_6.setStyleSheet("color: rgb(238, 122, 233);font: 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 370, 71, 41))
        self.label_7.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 420, 61, 41))
        self.label_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 470, 71, 41))
        self.label_9.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 520, 71, 41))
        self.label_10.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.pushButtonMH = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMH.setGeometry(QtCore.QRect(540, 130, 131, 41))
        self.pushButtonMH.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonMH.setObjectName("pushButtonMH")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 190, 101, 41))
        self.label_11.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.pushButtonGM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGM.setGeometry(QtCore.QRect(540, 390, 131, 41))
        self.pushButtonGM.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtonGM.setObjectName("pushButtonGM")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(540, 440, 101, 41))
        self.label_12.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.comboBoxMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMode.setGeometry(QtCore.QRect(110, 30, 111, 41))
        self.comboBoxMode.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 30, 81, 41))
        self.label_13.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.pushButtnReset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtnReset.setGeometry(QtCore.QRect(540, 290, 131, 41))
        self.pushButtnReset.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButtnReset.setObjectName("pushButtnReset")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(300, 30, 121, 41))
        self.label_14.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.comboBoxLength = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxLength.setGeometry(QtCore.QRect(410, 30, 111, 41))
        self.comboBoxLength.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.comboBoxLength.setObjectName("comboBoxLength")
        self.comboBoxLength.addItem("")
        self.comboBoxLength.addItem("")
        self.comboBoxLength.addItem("")

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(550, 30, 81, 41))
        self.label_15.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.comboBoxLength_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxLength_2.setGeometry(QtCore.QRect(640, 30, 111, 41))
        self.comboBoxLength_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.comboBoxLength_2.setObjectName("comboBoxLength_2")
        self.comboBoxLength_2.addItem("")
        self.comboBoxLength_2.addItem("")
        self.comboBoxLength_2.addItem("")

        self.MHbanro = QtWidgets.QLineEdit(self.centralwidget)
        self.MHbanro.setGeometry(QtCore.QRect(110, 120, 411, 41))
        self.MHbanro.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.MHbanro.setObjectName("MHbanro")
        self.MHbanro.setPlaceholderText('Chuỗi kí tự cần mã hoá')
        self.MHkey = QtWidgets.QLineEdit(self.centralwidget)
        self.MHkey.setGeometry(QtCore.QRect(110, 170, 411, 41))
        self.MHkey.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.MHkey.setObjectName("MHkey")
        self.MHkey.setPlaceholderText('Key là 32 hoặc 48 hoặc 64 kí tự a->f 0->9')
        self.MHiv = QtWidgets.QLineEdit(self.centralwidget)
        self.MHiv.setGeometry(QtCore.QRect(110, 220, 411, 41))
        self.MHiv.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.MHiv.setObjectName("MHiv")
        self.MHma = QtWidgets.QLineEdit(self.centralwidget)
        self.MHma.setGeometry(QtCore.QRect(110, 270, 411, 41))
        self.MHma.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.MHma.setObjectName("MHma")
        self.MHma.setReadOnly(True)
        self.GMma = QtWidgets.QLineEdit(self.centralwidget)
        self.GMma.setGeometry(QtCore.QRect(110, 370, 411, 41))
        self.GMma.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.GMma.setObjectName("GMma")
        self.GMma.setPlaceholderText('Chuỗi HEX cần giải mã có độ dài chẵn chỉ gồm kí tự 0->9 a->f ')
        self.GMkey = QtWidgets.QLineEdit(self.centralwidget)
        self.GMkey.setGeometry(QtCore.QRect(110, 420, 411, 41))
        self.GMkey.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.GMkey.setObjectName("GMkey")
        self.GMkey.setPlaceholderText('Key là 32 hoặc 48 hoặc 64 kí tự a->f 0->9')
        self.GMbanro = QtWidgets.QLineEdit(self.centralwidget)
        self.GMbanro.setGeometry(QtCore.QRect(110, 520, 411, 41))
        self.GMbanro.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.GMbanro.setObjectName("GMbanro")
        self.GMbanro.setReadOnly(True)
        self.GMiv = QtWidgets.QLineEdit(self.centralwidget)
        self.GMiv.setGeometry(QtCore.QRect(110, 470, 411, 41))
        self.GMiv.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.GMiv.setObjectName("GMiv")
        self.timeMahoa = QtWidgets.QLineEdit(self.centralwidget)
        self.timeMahoa.setGeometry(QtCore.QRect(540, 230, 201, 41))
        self.timeMahoa.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.timeMahoa.setObjectName("timeMahoa")
        self.timeGM = QtWidgets.QLineEdit(self.centralwidget)
        self.timeGM.setGeometry(QtCore.QRect(540, 480, 201, 41))
        self.timeGM.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.timeGM.setObjectName("timeGM")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButtonMH.clicked.connect(self.MaHoa)
        self.pushButtonGM.clicked.connect(self.GiaiMa)
        self.pushButtnReset.clicked.connect(self.Reset)
        self.comboBoxMode.activated.connect(self.checkCombobox)
        self.comboBoxLength_2.activated.connect(self.checkCode)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def checkCode(self):
        self.checkCombobox()
        if self.comboBoxLength_2.currentText() == 'HEX':
            self.MHbanro.setPlaceholderText('Nhập chuỗi hex có độ dài chẵn chỉ gồm kí tự 0->9 a->f')
            self.MHkey.setPlaceholderText('Key là 32 hoặc 48 hoặc 64 kí tự a->f 0->9')
            self.GMkey.setPlaceholderText('Key là 32 hoặc 48 hoặc 64 kí tự a->f 0->9')
        else:
            self.MHbanro.setPlaceholderText('Nhập chuỗi kí tự cần mã hoá')
            self.MHkey.setPlaceholderText('Key là chuỗi dài 16 hoặc 24 hoặc 32')
            self.GMkey.setPlaceholderText('Key là chuỗi dài 16 hoặc 24 hoặc 32')

    def checkCombobox(self):
        if self.comboBoxMode.currentText() == 'AES':
            self.MHiv.setReadOnly(True)
            self.MHiv.setPlaceholderText('')
            self.GMiv.setReadOnly(True)
            self.GMiv.setPlaceholderText('')
        else:
            self.GMiv.setReadOnly(False)
            self.MHiv.setReadOnly(False)
            if self.comboBoxLength_2.currentText() == 'HEX':
                self.GMiv.setPlaceholderText('iv là chuỗi 32 kí tự a->f 0->9')
                self.MHiv.setPlaceholderText('iv là chuỗi 32 kí tự a->f 0->9')
            else:
                self.GMiv.setPlaceholderText('iv là chuỗi có độ dài 16')
                self.MHiv.setPlaceholderText('iv là chuỗi có độ dài 16')

    def checkAll(self, key, iv, inp):
        lenth = self.comboBoxLength.currentText()
        if lenth == '128':
            lenth = 16
        elif lenth == '192':
            lenth = 24
        else:
            lenth = 32
        mode = self.comboBoxMode.currentText()
        code = self.comboBoxLength_2.currentText()
        if lenth * 2 != len(key) and code == 'HEX':
            QMessageBox.about(MainWindow, "Error","Mã hoá "+self.comboBoxLength.currentText() + " dài: " +str(lenth*2)+
                              "\nNhập sai, chiều dài key: " + str(len(key)))
            return 0
        elif len(iv) != 32 and code == 'HEX' and mode != 'AES':
            QMessageBox.about(MainWindow, "Error", "Chiều dài iv: 32\nNhập sai chiều dài iv: " + str(len(iv)))
            return 0

        if code != 'HEX':
            key = str.encode(key, code)
            iv = str.encode(iv, code)

        if lenth != len(key) and code != 'HEX':
            QMessageBox.about(MainWindow, "Error",
                              "Mã hoá " + self.comboBoxLength.currentText() + " dài: " + str(lenth) +
                              "\nNhập sai, chiều dài key: " + str(len(key)))
            return 0
        elif len(iv) != 16 and code != 'HEX' and mode != 'AES':
            QMessageBox.about(MainWindow, "Error", "Chiều dài iv: 16\nNhập sai chiều dài iv: " + str(len(iv)))
            return 0

        return 1
    def checkHEX(self, inp):
        for i in inp:
            if not i in '0123456789abcdef':
                return 0
        return 1

    def checkNullMH(self):
        key = self.MHkey.text()
        iv = self.MHiv.text()
        inp = self.MHbanro.text()
        if key=='' or inp == '' or (iv =='' and self.comboBoxMode.currentText() !='AES'):
            if self.comboBoxMode.currentText() !='AES':
                return 2
        if not self.checkHEX(inp) and self.comboBoxLength_2.currentText() == 'HEX':
            return 3
        if self.comboBoxLength_2 =='HEX' and len(inp)%2 :
            return 3
        if not self.checkAll(key, iv, inp):
            return 0
        return 1

    def MaHoa(self):
        if self.checkNullMH() == 1:
            key = self.MHkey.text()
            iv = self.MHiv.text()
            inp = self.MHbanro.text()
            mode = self.comboBoxMode.currentText()
            code =  self.comboBoxLength_2.currentText()

            if code == 'HEX':
                key = bytes.fromhex(key)
                if mode != 'AES':
                    iv = bytes.fromhex(iv)
                inp = bytes.fromhex(inp)
            else:
                key = str.encode(key, code)
                if mode != 'AES':
                    iv = str.encode(iv, code)
                inp = str.encode(inp, code)

            try:
                start = timeit.default_timer()

                encrypt = Choose.CHOOSE(mode, key, inp, iv).Encrypt()

                stop = timeit.default_timer()
                timeT = stop - start
                self.timeMahoa.setText(str(timeT) + 's')

                self.MHma.setText(encrypt.hex())
            except Exception as e:
                print(e)
                QMessageBox.about(MainWindow, "Error", "Error!")
        elif self.checkNullMH() == 2:
            QMessageBox.about(MainWindow , "Error", "Vui lòng nhập đủ tất cả trường!")
        elif self.checkNullMH() == 3:
            QMessageBox.about(MainWindow, "Error", "Input hex phải là chuỗi có độ dài chẵn! \nVà phải là các kí tự từ 0->9 a->f!")

    def checkNullGM(self):
        key = self.GMkey.text()
        iv = self.GMiv.text()
        inp = self.GMma.text()
        if key=='' or inp == '' or (iv =='' and self.comboBoxMode.currentText() !='AES'):
            return 2
        if not self.checkHEX(inp):
            return 3
        if len(inp)%2 :
            return 3
        if not self.checkAll(key, iv, inp):
            return 0
        return 1
    def GiaiMa(self):
        if self.checkNullGM() == 1:
            key = self.GMkey.text()
            inp = self.GMma.text()
            mode = self.comboBoxMode.currentText()
            iv  = ''
            if mode != 'AES':
                iv = self.GMiv.text()

            code = self.comboBoxLength_2.currentText()
            if code == 'HEX':
                key = bytes.fromhex(key)
                if mode != 'AES':
                    iv = bytes.fromhex(iv)
                inp = bytes.fromhex(inp)
            else:
                key = str.encode(key, code)
                if mode != 'AES':
                    iv = str.encode(iv, code)
                inp = bytes.fromhex(inp)

            try:
                start = timeit.default_timer()

                decrypt = Choose.CHOOSE(mode,key,inp, iv).Decrypt()

                stop = timeit.default_timer()
                timeT = stop - start

                if code == 'HEX':
                    text = decrypt.hex()
                else:
                    text = decrypt.decode(code)

                # text = str(decrypt)[2:len(decrypt)+2]
                # print(text)

                self.GMbanro.setText(text)
                self.timeGM.setText(str(timeT)+'s')
            except Exception as e:
                print(e)
                QMessageBox.about(MainWindow, "Error", "Error!")
        elif self.checkNullGM() == 2:
            QMessageBox.about(MainWindow , "Error", "Vui lòng nhập đủ tất cả trường!")
        elif self.checkNullMH() == 3:
            QMessageBox.about(MainWindow, "Error", "Input hex phải là chuỗi có độ dài chẵn! \nVà phải là các kí tự từ 0->9 a->f!")
    def Reset(self):
        self.MHbanro.setText('')
        self.MHkey.setText('')
        self.MHiv.setText('')
        self.MHma.setText('')
        self.GMma.setText('')
        self.GMkey.setText('')
        self.GMiv.setText('')
        self.GMbanro.setText('')
        self.timeMahoa.setText('')
        self.timeGM.setText('')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mã Hoá AES"))
        MainWindow.setWindowIcon(QtGui.QIcon('icon.ico'))
        self.label.setText(_translate("MainWindow", "Bản rõ:"))
        self.label_2.setText(_translate("MainWindow", "Key:"))
        self.label_3.setText(_translate("MainWindow", "iv:"))
        self.label_4.setText(_translate("MainWindow", "Mã:"))
        self.label_5.setText(_translate("MainWindow", "Mã hóa"))
        self.label_6.setText(_translate("MainWindow", "Giải Mã"))
        self.label_7.setText(_translate("MainWindow", "Mã:"))
        self.label_8.setText(_translate("MainWindow", "Key:"))
        self.label_9.setText(_translate("MainWindow", "iv:"))
        self.label_10.setText(_translate("MainWindow", "Bản rõ:"))
        self.pushButtonMH.setText(_translate("MainWindow", "Mã hóa"))
        self.label_11.setText(_translate("MainWindow", "Time:"))
        self.pushButtonGM.setText(_translate("MainWindow", "Giải mã"))
        self.label_12.setText(_translate("MainWindow", "Time:"))
        self.comboBoxMode.setItemText(0, _translate("MainWindow", "AES"))
        self.comboBoxMode.setItemText(1, _translate("MainWindow", "AES_CBC"))
        self.comboBoxMode.setItemText(2, _translate("MainWindow", "AES_PCBC"))
        self.comboBoxMode.setItemText(3, _translate("MainWindow", "AES_CFB"))
        self.comboBoxMode.setItemText(4, _translate("MainWindow", "AES_OFB"))
        self.comboBoxMode.setItemText(5, _translate("MainWindow", "AES_CTR"))
        self.label_13.setText(_translate("MainWindow", "Mode:"))
        self.pushButtnReset.setText(_translate("MainWindow", "Reset"))
        self.label_14.setText(_translate("MainWindow", "Độ dài khóa:"))
        self.comboBoxLength.setItemText(0, _translate("MainWindow", "128"))
        self.comboBoxLength.setItemText(1, _translate("MainWindow", "192"))
        self.comboBoxLength.setItemText(2, _translate("MainWindow", "256"))
        self.label_15.setText(_translate("MainWindow", "Bản Mã:"))
        self.comboBoxLength_2.setItemText(0, _translate("MainWindow", "HEX"))
        self.comboBoxLength_2.setItemText(1, _translate("MainWindow", "UTF-8"))
        self.comboBoxLength_2.setItemText(2, _translate("MainWindow", "UTF16"))
        self.checkCode()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
